In [5]:
import tensorflow as tf
mat0 = tf.constant([[0,0,0],[0,0,0]])
mat1 = tf.zeros([2,3])
mat2 = tf.ones([3,2])
mat3 = tf.fill([2,3],15)
with tf.Session() as sess:
    #print(sess.run(mat0))
    #print(sess.run(mat1))
    #print(sess.run(mat2))
    print(sess.run(mat3))

[[15 15 15]
 [15 15 15]]


In [14]:
import tensorflow as tf
mat1 = tf.constant([[2],[3],[4]])
mat2 = tf.zeros_like(mat1)
mat3 = tf.linspace(0.0,2.0,11)
mat4 = tf.random_uniform([2,3],-1,2)
with tf.Session() as sess:
    print(sess.run(mat2))
    print(sess.run(mat3))
    print(sess.run(mat4))

[[0]
 [0]
 [0]]
[ 0.          0.2         0.40000001  0.60000002  0.80000001  1.
  1.20000005  1.39999998  1.60000002  1.80000007  2.        ]
[[ -1.66177750e-04   7.87446260e-01  -4.10951853e-01]
 [ -9.58950400e-01   1.97116375e-01  -2.69421697e-01]]
